In [1]:
import numpy as np
# Import the numpy python library


# Indexing, Slicing and iteration

In [11]:
a = np.arange(50).reshape(5, 2, 5)
# create a numpy array
print a

[[[ 0  1  2  3  4]
  [ 5  6  7  8  9]]

 [[10 11 12 13 14]
  [15 16 17 18 19]]

 [[20 21 22 23 24]
  [25 26 27 28 29]]

 [[30 31 32 33 34]
  [35 36 37 38 39]]

 [[40 41 42 43 44]
  [45 46 47 48 49]]]


### Indexing

In [36]:
print 'a[1]\n\n', a[1]
print '\na[1][1][2]\n\n', a[1][1][2]
# Another way to represent the above index is as follows
print a[1,1,2]
# My personal preference is to use the square brackets

a[1]

[[10 11 12 13 14]
 [15 16 17 18 19]]

a[1][1][2]

17
17


In [33]:
# Multidimensional array creation
b = np.fromfunction(function = lambda x, y : 10*x + y, shape = (5, 4), dtype = int)
print b
# print the array

[[ 0  1  2  3]
 [10 11 12 13]
 [20 21 22 23]
 [30 31 32 33]
 [40 41 42 43]]


## Slicing


In [57]:
print b[1:4,1:3], '\n\n'
# slice from row indices 1 to 3 and column indices 1 to 2... 
print b[1:4:2, ::2], '\n\n'
# slice from row indices 1 to 3 and column indices 0 to 4 with step 2 applied to both..

[[11 12]
 [21 22]
 [31 32]] 


[[10 12]
 [30 32]] 




In [74]:
print a, '\n---------------------------------'
# printing out array "a".
print a[0:4:2, 1, :5:2]
# slicing out the 3-D array with step applied
print '---------------------------------'

[[[ 0  1  2  3  4]
  [ 5  6  7  8  9]]

 [[10 11 12 13 14]
  [15 16 17 18 19]]

 [[20 21 22 23 24]
  [25 26 27 28 29]]

 [[30 31 32 33 34]
  [35 36 37 38 39]]

 [[40 41 42 43 44]
  [45 46 47 48 49]]] 
---------------------------------
[[ 5  7  9]
 [25 27 29]]
---------------------------------


## The dot notation with numpy

The "..." (three continous dots in the numpy slicing corresponds to as many colons needed by the numpy array to fullfill the slicing criteria..).

Examples are given below.

In [94]:
c = np.arange(256).reshape(4,4,4,4)
# create a 5-D array
print c 
# print out the array

[[[[  0   1   2   3]
   [  4   5   6   7]
   [  8   9  10  11]
   [ 12  13  14  15]]

  [[ 16  17  18  19]
   [ 20  21  22  23]
   [ 24  25  26  27]
   [ 28  29  30  31]]

  [[ 32  33  34  35]
   [ 36  37  38  39]
   [ 40  41  42  43]
   [ 44  45  46  47]]

  [[ 48  49  50  51]
   [ 52  53  54  55]
   [ 56  57  58  59]
   [ 60  61  62  63]]]


 [[[ 64  65  66  67]
   [ 68  69  70  71]
   [ 72  73  74  75]
   [ 76  77  78  79]]

  [[ 80  81  82  83]
   [ 84  85  86  87]
   [ 88  89  90  91]
   [ 92  93  94  95]]

  [[ 96  97  98  99]
   [100 101 102 103]
   [104 105 106 107]
   [108 109 110 111]]

  [[112 113 114 115]
   [116 117 118 119]
   [120 121 122 123]
   [124 125 126 127]]]


 [[[128 129 130 131]
   [132 133 134 135]
   [136 137 138 139]
   [140 141 142 143]]

  [[144 145 146 147]
   [148 149 150 151]
   [152 153 154 155]
   [156 157 158 159]]

  [[160 161 162 163]
   [164 165 166 167]
   [168 169 170 171]
   [172 173 174 175]]

  [[176 177 178 179]
   [180 181 182 183]
   [184 

In [100]:
# slicing with the dot notation.
print c[1::2, ...]
# display the array
print '----------------------------'
print c[1::2, ..., 1, 1]
print '----------------------------'

[[[[ 64  65  66  67]
   [ 68  69  70  71]
   [ 72  73  74  75]
   [ 76  77  78  79]]

  [[ 80  81  82  83]
   [ 84  85  86  87]
   [ 88  89  90  91]
   [ 92  93  94  95]]

  [[ 96  97  98  99]
   [100 101 102 103]
   [104 105 106 107]
   [108 109 110 111]]

  [[112 113 114 115]
   [116 117 118 119]
   [120 121 122 123]
   [124 125 126 127]]]


 [[[192 193 194 195]
   [196 197 198 199]
   [200 201 202 203]
   [204 205 206 207]]

  [[208 209 210 211]
   [212 213 214 215]
   [216 217 218 219]
   [220 221 222 223]]

  [[224 225 226 227]
   [228 229 230 231]
   [232 233 234 235]
   [236 237 238 239]]

  [[240 241 242 243]
   [244 245 246 247]
   [248 249 250 251]
   [252 253 254 255]]]]
----------------------------
[[ 69  85 101 117]
 [197 213 229 245]]
----------------------------


## Iteration of arrays



In [115]:
print b
# print out array b

print "Iteration through each row"
for row in b:
    # iterate through the rows
    print row
    # print each row
    
print "Iterate through each column"
for col in b.T:
    # iterate through each column
    print col
    # print each col
    
print "Iterate through each element using 'flat' which returns an flattened iterator, only iterates row wise.."
for ele in b.flat:
    # iterate through each element
    # elements are iterated based on each row
    print ele,
    
print "\nIterate through each element using flatten function, with order C(Contigous) meaning row wise"
for ele in b.flatten(order = 'C'):
    # copy of flattened array
    print ele, 
    
print "\nIterate through each element using flatten function, with order F(Fortran) meaning column wise"
for ele in b.flatten(order = 'F'):
    # copy of the flattened array
    print ele,

[[ 0  1  2  3]
 [10 11 12 13]
 [20 21 22 23]
 [30 31 32 33]
 [40 41 42 43]]
Iteration through each row
[0 1 2 3]
[10 11 12 13]
[20 21 22 23]
[30 31 32 33]
[40 41 42 43]
Iterate through each column
[ 0 10 20 30 40]
[ 1 11 21 31 41]
[ 2 12 22 32 42]
[ 3 13 23 33 43]
Iterate through each element using 'flat' which returns an flattened iterator, only iterates row wise..
0 1 2 3 10 11 12 13 20 21 22 23 30 31 32 33 40 41 42 43 
Iterate through each element using flatten function, with order C(Contigous) meaning row wise
0 1 2 3 10 11 12 13 20 21 22 23 30 31 32 33 40 41 42 43 
Iterate through each element using flatten function, with order F(Fortran) meaning column wise
0 10 20 30 40 1 11 21 31 41 2 12 22 32 42 3 13 23 33 43


# Shape manipulation of numpy array

The following are the methods by which the shape of the array can be modified as follows

1. ravel - Helps in flattening the array, with the order argument we can specify the row(C - Contigous) or column(F - Fortran) flatten.
2. flatten and flat as we saw above.
3. shape: Directly specifying the shape of the array, can have an effect too.
4. T: taking the transpose of the array.
5. reshape: The reshape takes the arguments of the shape and returns a new modified array. Giving -1 as an argument makes the reshape method itself to work the shape of the array. The reshape takes the order as an argument too.
6. resize: The resize takes the desired shape as an argument and it returns None and directly modifies the array itself. Like how the sort works on array or on a list. More to read on the documentation.

In [132]:
arr = np.floor(10*np.random.random((3,4)))
# create an array
print arr
# print out the array
print "Shape", arr.shape
# print the shape of the array
print "Rank", arr.ndim
# print the no of dim of the array or its rank

[[ 4.  6.  0.  4.]
 [ 9.  9.  4.  4.]
 [ 5.  5.  9.  6.]]
Shape (3, 4)
Rank 2


In [133]:
print "The ravel method"
# The ravel method is used to flatten the array.
print "Row wise flatten", arr.ravel(order = 'C') 
# print the array row wise (the default - Contigous order)
print "Column wise flatten", arr.ravel(order = 'F')
# print the array column wise flattened (Fortran order)

The ravel method
Row wise flatten [ 4.  6.  0.  4.  9.  9.  4.  4.  5.  5.  9.  6.]
Column wise flatten [ 4.  9.  5.  6.  9.  5.  0.  4.  9.  4.  4.  6.]


In [134]:
# Directly changing the shape of the array
print arr
print "Shape", arr.shape
arr.shape = (6, 2)
# change the shape of the array to (6,2)
print arr
print "New shape", arr.shape

[[ 4.  6.  0.  4.]
 [ 9.  9.  4.  4.]
 [ 5.  5.  9.  6.]]
Shape (3, 4)
[[ 4.  6.]
 [ 0.  4.]
 [ 9.  9.]
 [ 4.  4.]
 [ 5.  5.]
 [ 9.  6.]]
New shape (6, 2)


In [135]:
# change shape by taking the transpose of the array
print arr.T
print "Shape with transpose", arr.T.shape

[[ 4.  0.  9.  4.  5.  9.]
 [ 6.  4.  9.  4.  5.  6.]]
Shape with transpose (2, 6)


In [142]:
# Reshape method
print "Array\n", arr

print "Reshaped to (4, 3)\n", arr.reshape(4, 3, order = 'C')
# Reshaped with row wise order (C - contigous)
print "Reshaped with (4, 3)\n", arr.reshape(4, 3, order = 'F')
# reshaped with column wise order F - Fortran

Array
[[ 4.  6.]
 [ 0.  4.]
 [ 9.  9.]
 [ 4.  4.]
 [ 5.  5.]
 [ 9.  6.]]
Reshaped to (4, 3)
[[ 4.  6.  0.]
 [ 4.  9.  9.]
 [ 4.  4.  5.]
 [ 5.  9.  6.]]
Reshaped with (4, 3)
[[ 4.  5.  9.]
 [ 0.  9.  4.]
 [ 9.  6.  5.]
 [ 4.  4.  6.]]


In [143]:
# resize method
print "Array\n", arr


Array
[[ 4.  6.]
 [ 0.  4.]
 [ 9.  9.]
 [ 4.  4.]
 [ 5.  5.]
 [ 9.  6.]]
